//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Services.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillSetttings
    {
        public string partner { get; set; }
        public string return_url { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public string out_trade_no { get; set; }
        public float total_fee { get; set; }
        public string seller_email { get; set; }
        public string key { get; set; }
        public string sign { get; set; }
        public string gatewayurl { get; set; }
    }
}
