//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Services.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public Books()
        {
            this.Cart = new HashSet<Cart>();
            this.OrderBook = new HashSet<OrderBook>();
        }
    
        public int id { get; set; }
        public string author { get; set; }
        public string isbn { get; set; }
        public System.DateTime publishdate { get; set; }
        public int wordscount { get; set; }
        public float unitprice { get; set; }
        public string contentdescription { get; set; }
        public string editorcomment { get; set; }
        public string toc { get; set; }
        public int clicks { get; set; }
        public int categoryid { get; set; }
        public int publisherid { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Publishers Publishers { get; set; }
        public virtual ICollection<Cart> Cart { get; set; }
        public virtual ICollection<OrderBook> OrderBook { get; set; }
    }
}
