//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Diagnostics.Contracts;

namespace BookShop.Services.EntityModels
{
	[ContractClass(typeof(RepositoryContract<>))]
    public interface IRepository<E> : IReadOnlyRepository<E>
    {
        void Add(E entity);
        void Remove(E entity);
        int Save();
    }
}

