//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Services.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleInfo
    {
        public RoleInfo()
        {
            this.RoleRight = new HashSet<RoleRight>();
            this.Users = new HashSet<Users>();
        }
    
        public int id { get; set; }
        public string roledesc { get; set; }
        public string rolename { get; set; }
    
        public virtual ICollection<RoleRight> RoleRight { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
