//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Services.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysFun
    {
        public SysFun()
        {
            this.RoleRight = new HashSet<RoleRight>();
        }
    
        public int id { get; set; }
        public string displayname { get; set; }
        public string nodeurl { get; set; }
        public int displayorder { get; set; }
        public int parentnodeid { get; set; }
    
        public virtual ICollection<RoleRight> RoleRight { get; set; }
    }
}
