//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Services.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Cart = new HashSet<Cart>();
            this.Orders = new HashSet<Orders>();
            this.PayInfo = new HashSet<PayInfo>();
        }
    
        public int id { get; set; }
        public string loginid { get; set; }
        public string loginpwd { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string mail { get; set; }
        public decimal money { get; set; }
        public int userstateid { get; set; }
        public int roleinfoid { get; set; }
    
        public virtual ICollection<Cart> Cart { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<PayInfo> PayInfo { get; set; }
        public virtual RoleInfo RoleInfo { get; set; }
        public virtual UserStates UserStates { get; set; }
    }
}
